In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
### sentences
sent={'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',
      'your videos are good',
}

In [4]:
sent

{'I am a good boy',
 'I am a good developer',
 'the cup of tea',
 'the glass of juice',
 'the glass of milk',
 'understand the meaning of words',
 'your videos are good'}

In [5]:
# Define the vocabulary size
voc_size=10000

In [6]:
### One hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4144, 2469, 1190, 5928],
 [1686, 1466, 6822, 7217, 6751],
 [4144, 463, 1190, 6990],
 [1686, 1466, 6822, 7217, 5827],
 [4592, 5903, 2665, 7217],
 [4144, 463, 1190, 9081],
 [7236, 4144, 2954, 1190, 1618]]

In [7]:
## word embedding representaion
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy  as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)## this line helps in making vetors of the defined length.Here when the sentence of the given length is not satisfied 0 are added in the beginning.
print(embedded_docs)

[[   0    0    0    0 4144 2469 1190 5928]
 [   0    0    0 1686 1466 6822 7217 6751]
 [   0    0    0    0 4144  463 1190 6990]
 [   0    0    0 1686 1466 6822 7217 5827]
 [   0    0    0    0 4592 5903 2665 7217]
 [   0    0    0    0 4144  463 1190 9081]
 [   0    0    0 7236 4144 2954 1190 1618]]


In [13]:
# feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.02531446,  0.02108731,  0.04786279,  0.0204666 , -0.02407427,
        -0.02071434, -0.03086921,  0.0147298 ,  0.00323765,  0.02727108],
       [ 0.02531446,  0.02108731,  0.04786279,  0.0204666 , -0.02407427,
        -0.02071434, -0.03086921,  0.0147298 ,  0.00323765,  0.02727108],
       [ 0.02531446,  0.02108731,  0.04786279,  0.0204666 , -0.02407427,
        -0.02071434, -0.03086921,  0.0147298 ,  0.00323765,  0.02727108],
       [ 0.02531446,  0.02108731,  0.04786279,  0.0204666 , -0.02407427,
        -0.02071434, -0.03086921,  0.0147298 ,  0.00323765,  0.02727108],
       [-0.03260304, -0.02158073,  0.04410397, -0.04277778,  0.03943965,
        -0.03153591,  0.04160123,  0.02429009, -0.03920164,  0.01260045],
       [-0.04120589, -0.00587891, -0.02502635, -0.0480573 , -0.01532441,
         0.04787153, -0.02503849, -0.01378845,  0.02100564, -0.01805487],
       [-0.01635311,  0.03545826,  0.04380747, -0.01786817,  0.01525151,
        -0.0008754 ,  0.04752246,  0.04762972